spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 147258
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  rabbitmq:
    addresses: 43.142.181.137
    port: 5672
    username: guest
    password: 13110197267ljlLJL!
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
wx:
  appId: wx3e6b9f1c5a7ff034
  mchId: 1614433647
  mchKey: Aa111111111122222222223333333333
  notifyUrl: http://127.0.0.1:8081/pay/notify
  returnUrl: https://www.bilibili.com/v/popular/all/?spm_id_from=333.1007.0.0
server:
  port: 8081